// Code generated by protoc-gen-go.
// source: errorpb.proto
// DO NOT EDIT!

/*
Package errorpb is a generated protocol buffer package.

It is generated from these files:
	errorpb.proto

It has these top-level messages:
	NotLeaderError
	RegionNotFoundError
	KeyNotInRegion
	StaleEpoch
	Error
*/
package errorpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import metapb "github.com/pingcap/kvproto/pkg/metapb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type NotLeaderError struct {
	RegionId         *uint64      `protobuf:"varint,1,opt,name=region_id" json:"region_id,omitempty"`
	Leader           *metapb.Peer `protobuf:"bytes,2,opt,name=leader" json:"leader,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NotLeaderError) Reset()                    { *m = NotLeaderError{} }
func (m *NotLeaderError) String() string            { return proto.CompactTextString(m) }
func (*NotLeaderError) ProtoMessage()               {}
func (*NotLeaderError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NotLeaderError) GetRegionId() uint64 {
	if m != nil && m.RegionId != nil {
		return *m.RegionId
	}
	return 0
}

func (m *NotLeaderError) GetLeader() *metapb.Peer {
	if m != nil {
		return m.Leader
	}
	return nil
}

type RegionNotFoundError struct {
	RegionId         *uint64 `protobuf:"varint,1,opt,name=region_id" json:"region_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RegionNotFoundError) Reset()                    { *m = RegionNotFoundError{} }
func (m *RegionNotFoundError) String() string            { return proto.CompactTextString(m) }
func (*RegionNotFoundError) ProtoMessage()               {}
func (*RegionNotFoundError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegionNotFoundError) GetRegionId() uint64 {
	if m != nil && m.RegionId != nil {
		return *m.RegionId
	}
	return 0
}

type KeyNotInRegion struct {
	Key              []byte  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	RegionId         *uint64 `protobuf:"varint,2,opt,name=region_id" json:"region_id,omitempty"`
	StartKey         []byte  `protobuf:"bytes,3,opt,name=start_key" json:"start_key,omitempty"`
	EndKey           []byte  `protobuf:"bytes,4,opt,name=end_key" json:"end_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KeyNotInRegion) Reset()                    { *m = KeyNotInRegion{} }
func (m *KeyNotInRegion) String() string            { return proto.CompactTextString(m) }
func (*KeyNotInRegion) ProtoMessage()               {}
func (*KeyNotInRegion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *KeyNotInRegion) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyNotInRegion) GetRegionId() uint64 {
	if m != nil && m.RegionId != nil {
		return *m.RegionId
	}
	return 0
}

func (m *KeyNotInRegion) GetStartKey() []byte {
	if m != nil {
		return m.StartKey
	}
	return nil
}

func (m *KeyNotInRegion) GetEndKey() []byte {
	if m != nil {
		return m.EndKey
	}
	return nil
}

type StaleEpoch struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *StaleEpoch) Reset()                    { *m = StaleEpoch{} }
func (m *StaleEpoch) String() string            { return proto.CompactTextString(m) }
func (*StaleEpoch) ProtoMessage()               {}
func (*StaleEpoch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Error struct {
	Message          *string              `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	NotLeader        *NotLeaderError      `protobuf:"bytes,2,opt,name=not_leader" json:"not_leader,omitempty"`
	RegionNotFound   *RegionNotFoundError `protobuf:"bytes,3,opt,name=region_not_found" json:"region_not_found,omitempty"`
	KeyNotInRegion   *KeyNotInRegion      `protobuf:"bytes,4,opt,name=key_not_in_region" json:"key_not_in_region,omitempty"`
	StaleEpoch       *StaleEpoch          `protobuf:"bytes,5,opt,name=stale_epoch" json:"stale_epoch,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Error) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *Error) GetNotLeader() *NotLeaderError {
	if m != nil {
		return m.NotLeader
	}
	return nil
}

func (m *Error) GetRegionNotFound() *RegionNotFoundError {
	if m != nil {
		return m.RegionNotFound
	}
	return nil
}

func (m *Error) GetKeyNotInRegion() *KeyNotInRegion {
	if m != nil {
		return m.KeyNotInRegion
	}
	return nil
}

func (m *Error) GetStaleEpoch() *StaleEpoch {
	if m != nil {
		return m.StaleEpoch
	}
	return nil
}

func init() {
	proto.RegisterType((*NotLeaderError)(nil), "errorpb.NotLeaderError")
	proto.RegisterType((*RegionNotFoundError)(nil), "errorpb.RegionNotFoundError")
	proto.RegisterType((*KeyNotInRegion)(nil), "errorpb.KeyNotInRegion")
	proto.RegisterType((*StaleEpoch)(nil), "errorpb.StaleEpoch")
	proto.RegisterType((*Error)(nil), "errorpb.Error")
}

var fileDescriptor0 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x95, 0xfe, 0xa1, 0xea, 0x25, 0x14, 0xea, 0x0e, 0x44, 0xa8, 0x03, 0xf2, 0x14, 0x09,
	0x29, 0x43, 0x06, 0x76, 0x86, 0x22, 0x21, 0x10, 0x42, 0xc0, 0x6e, 0x19, 0x72, 0x94, 0x88, 0xd6,
	0x8e, 0x6c, 0x33, 0xf4, 0xb3, 0xf2, 0x65, 0xb0, 0x2f, 0x69, 0xa1, 0x11, 0x1d, 0x7d, 0xfe, 0xbd,
	0x77, 0xef, 0x1d, 0x1c, 0xa3, 0x31, 0xda, 0xd4, 0xaf, 0x79, 0x6d, 0xb4, 0xd3, 0x6c, 0xd4, 0x3e,
	0xcf, 0x93, 0x35, 0x3a, 0xb9, 0x1d, 0xf3, 0x6b, 0x98, 0x3c, 0x68, 0x77, 0x8f, 0xb2, 0x44, 0xb3,
	0x08, 0x04, 0x9b, 0xc2, 0xd8, 0xe0, 0xb2, 0xd2, 0x4a, 0x54, 0x65, 0x1a, 0x5d, 0x44, 0xd9, 0x80,
	0xcd, 0xe1, 0x68, 0x45, 0x44, 0xda, 0xf3, 0xef, 0xb8, 0x48, 0xf2, 0xd6, 0xe3, 0x11, 0xd1, 0xf0,
	0x0c, 0x66, 0x4f, 0x24, 0xf0, 0x46, 0x37, 0xfa, 0x4b, 0x95, 0x87, 0x7c, 0xf8, 0x0b, 0x4c, 0xee,
	0x70, 0xe3, 0xb1, 0x5b, 0xd5, 0x28, 0x58, 0x0c, 0xfd, 0x4f, 0xdc, 0xd0, 0x77, 0xb2, 0xaf, 0xe8,
	0xd1, 0x66, 0x3f, 0xb2, 0x4e, 0x1a, 0x27, 0x02, 0xd5, 0x27, 0xea, 0x04, 0x46, 0xa8, 0x4a, 0x1a,
	0x0c, 0xc2, 0x80, 0x27, 0x00, 0xcf, 0x4e, 0xae, 0x70, 0x51, 0xeb, 0xb7, 0x0f, 0xfe, 0x1d, 0xc1,
	0xb0, 0x09, 0xe0, 0xc1, 0x35, 0x5a, 0x2b, 0x97, 0x48, 0xfe, 0x63, 0x76, 0x09, 0xa0, 0xb4, 0x13,
	0x7b, 0x55, 0xce, 0xf2, 0xed, 0x99, 0x3a, 0x67, 0xb8, 0x82, 0xd3, 0x36, 0x4c, 0xd0, 0xbc, 0x87,
	0x5e, 0x14, 0x20, 0x2e, 0xe6, 0x3b, 0xc9, 0x7f, 0xb5, 0x0b, 0x98, 0xfa, 0x68, 0x24, 0xaa, 0x94,
	0x68, 0x2c, 0x28, 0xe8, 0xdf, 0x5d, 0x9d, 0x2b, 0x64, 0x10, 0xdb, 0xd0, 0x40, 0x60, 0xa8, 0x90,
	0x0e, 0x89, 0x9e, 0xed, 0xe8, 0xdf, 0x76, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x96, 0x2c,
	0xb9, 0xd5, 0x01, 0x00, 0x00,
}
