// Code generated by protoc-gen-go.
// source: raft_cmdpb.proto
// DO NOT EDIT!

/*
Package raft_cmdpb is a generated protocol buffer package.

It is generated from these files:
	raft_cmdpb.proto

It has these top-level messages:
	GetRequest
	GetResponse
	SeekRequest
	SeekResponse
	PutRequest
	PutResponse
	DeleteRequest
	DeleteResponse
	Request
	Response
	ChangePeerRequest
	ChangePeerResponse
	SplitRequest
	SplitResponse
	CompactLogRequest
	CompactLogResponse
	AdminRequest
	AdminResponse
	RegionLeaderRequest
	RegionLeaderResponse
	RegionDetailRequest
	RegionDetailResponse
	StatusRequest
	StatusResponse
	RaftRequestHeader
	RaftResponseHeader
	RaftCommandRequest
	RaftCommandResponse
*/
package raft_cmdpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import metapb "github.com/pingcap/kvproto/pkg/metapb"
import errorpb "github.com/pingcap/kvproto/pkg/errorpb"
import raftpb "github.com/pingcap/kvproto/pkg/raftpb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CommandType int32

const (
	CommandType_Invalid CommandType = 0
	CommandType_Get     CommandType = 1
	CommandType_Seek    CommandType = 2
	CommandType_Put     CommandType = 3
	CommandType_Delete  CommandType = 4
)

var CommandType_name = map[int32]string{
	0: "Invalid",
	1: "Get",
	2: "Seek",
	3: "Put",
	4: "Delete",
}
var CommandType_value = map[string]int32{
	"Invalid": 0,
	"Get":     1,
	"Seek":    2,
	"Put":     3,
	"Delete":  4,
}

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}
func (x CommandType) String() string {
	return proto.EnumName(CommandType_name, int32(x))
}
func (x *CommandType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CommandType_value, data, "CommandType")
	if err != nil {
		return err
	}
	*x = CommandType(value)
	return nil
}
func (CommandType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AdminCommandType int32

const (
	AdminCommandType_InvalidAdmin AdminCommandType = 0
	AdminCommandType_ChangePeer   AdminCommandType = 1
	AdminCommandType_Split        AdminCommandType = 2
	AdminCommandType_CompactLog   AdminCommandType = 3
)

var AdminCommandType_name = map[int32]string{
	0: "InvalidAdmin",
	1: "ChangePeer",
	2: "Split",
	3: "CompactLog",
}
var AdminCommandType_value = map[string]int32{
	"InvalidAdmin": 0,
	"ChangePeer":   1,
	"Split":        2,
	"CompactLog":   3,
}

func (x AdminCommandType) Enum() *AdminCommandType {
	p := new(AdminCommandType)
	*p = x
	return p
}
func (x AdminCommandType) String() string {
	return proto.EnumName(AdminCommandType_name, int32(x))
}
func (x *AdminCommandType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AdminCommandType_value, data, "AdminCommandType")
	if err != nil {
		return err
	}
	*x = AdminCommandType(value)
	return nil
}
func (AdminCommandType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type StatusCommandType int32

const (
	StatusCommandType_InvalidStatus StatusCommandType = 0
	StatusCommandType_RegionLeader  StatusCommandType = 1
	StatusCommandType_RegionDetail  StatusCommandType = 2
)

var StatusCommandType_name = map[int32]string{
	0: "InvalidStatus",
	1: "RegionLeader",
	2: "RegionDetail",
}
var StatusCommandType_value = map[string]int32{
	"InvalidStatus": 0,
	"RegionLeader":  1,
	"RegionDetail":  2,
}

func (x StatusCommandType) Enum() *StatusCommandType {
	p := new(StatusCommandType)
	*p = x
	return p
}
func (x StatusCommandType) String() string {
	return proto.EnumName(StatusCommandType_name, int32(x))
}
func (x *StatusCommandType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StatusCommandType_value, data, "StatusCommandType")
	if err != nil {
		return err
	}
	*x = StatusCommandType(value)
	return nil
}
func (StatusCommandType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetRequest struct {
	Key              []byte `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetResponse struct {
	Value            []byte `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SeekRequest struct {
	Key              []byte `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SeekRequest) Reset()                    { *m = SeekRequest{} }
func (m *SeekRequest) String() string            { return proto.CompactTextString(m) }
func (*SeekRequest) ProtoMessage()               {}
func (*SeekRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SeekRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type SeekResponse struct {
	Key              []byte `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            []byte `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SeekResponse) Reset()                    { *m = SeekResponse{} }
func (m *SeekResponse) String() string            { return proto.CompactTextString(m) }
func (*SeekResponse) ProtoMessage()               {}
func (*SeekResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SeekResponse) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SeekResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PutRequest struct {
	Key              []byte `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            []byte `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PutRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PutResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type DeleteRequest struct {
	Key              []byte `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type DeleteResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Request struct {
	CmdType          *CommandType   `protobuf:"varint,1,opt,name=cmd_type,enum=raft_cmdpb.CommandType" json:"cmd_type,omitempty"`
	Get              *GetRequest    `protobuf:"bytes,2,opt,name=get" json:"get,omitempty"`
	Seek             *SeekRequest   `protobuf:"bytes,3,opt,name=seek" json:"seek,omitempty"`
	Put              *PutRequest    `protobuf:"bytes,4,opt,name=put" json:"put,omitempty"`
	Delete           *DeleteRequest `protobuf:"bytes,5,opt,name=delete" json:"delete,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Request) GetCmdType() CommandType {
	if m != nil && m.CmdType != nil {
		return *m.CmdType
	}
	return CommandType_Invalid
}

func (m *Request) GetGet() *GetRequest {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Request) GetSeek() *SeekRequest {
	if m != nil {
		return m.Seek
	}
	return nil
}

func (m *Request) GetPut() *PutRequest {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *Request) GetDelete() *DeleteRequest {
	if m != nil {
		return m.Delete
	}
	return nil
}

type Response struct {
	CmdType          *CommandType    `protobuf:"varint,1,opt,name=cmd_type,enum=raft_cmdpb.CommandType" json:"cmd_type,omitempty"`
	Get              *GetResponse    `protobuf:"bytes,2,opt,name=get" json:"get,omitempty"`
	Seek             *SeekResponse   `protobuf:"bytes,3,opt,name=seek" json:"seek,omitempty"`
	Put              *PutResponse    `protobuf:"bytes,4,opt,name=put" json:"put,omitempty"`
	Delete           *DeleteResponse `protobuf:"bytes,5,opt,name=delete" json:"delete,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Response) GetCmdType() CommandType {
	if m != nil && m.CmdType != nil {
		return *m.CmdType
	}
	return CommandType_Invalid
}

func (m *Response) GetGet() *GetResponse {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Response) GetSeek() *SeekResponse {
	if m != nil {
		return m.Seek
	}
	return nil
}

func (m *Response) GetPut() *PutResponse {
	if m != nil {
		return m.Put
	}
	return nil
}

func (m *Response) GetDelete() *DeleteResponse {
	if m != nil {
		return m.Delete
	}
	return nil
}

type ChangePeerRequest struct {
	ChangeType       *raftpb.ConfChangeType `protobuf:"varint,1,opt,name=change_type,enum=raftpb.ConfChangeType" json:"change_type,omitempty"`
	Peer             *metapb.Peer           `protobuf:"bytes,2,opt,name=peer" json:"peer,omitempty"`
	Region           *metapb.Region         `protobuf:"bytes,3,opt,name=region" json:"region,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *ChangePeerRequest) Reset()                    { *m = ChangePeerRequest{} }
func (m *ChangePeerRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangePeerRequest) ProtoMessage()               {}
func (*ChangePeerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ChangePeerRequest) GetChangeType() raftpb.ConfChangeType {
	if m != nil && m.ChangeType != nil {
		return *m.ChangeType
	}
	return raftpb.ConfChangeType_AddNode
}

func (m *ChangePeerRequest) GetPeer() *metapb.Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *ChangePeerRequest) GetRegion() *metapb.Region {
	if m != nil {
		return m.Region
	}
	return nil
}

type ChangePeerResponse struct {
	Region           *metapb.Region `protobuf:"bytes,1,opt,name=region" json:"region,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ChangePeerResponse) Reset()                    { *m = ChangePeerResponse{} }
func (m *ChangePeerResponse) String() string            { return proto.CompactTextString(m) }
func (*ChangePeerResponse) ProtoMessage()               {}
func (*ChangePeerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ChangePeerResponse) GetRegion() *metapb.Region {
	if m != nil {
		return m.Region
	}
	return nil
}

type SplitRequest struct {
	// The split_key must be in the been splitting region.
	// If the split_key is none, we will choose a proper key
	// to split the region in half.
	SplitKey []byte `protobuf:"bytes,1,opt,name=split_key" json:"split_key,omitempty"`
	// We split the region into two, first uses the origin
	// parent region id, and the second uses the new_region_id.
	// We must guarantee that the new_region_id is global unique.
	NewRegionId *uint64 `protobuf:"varint,2,opt,name=new_region_id" json:"new_region_id,omitempty"`
	// The peer ids for the new split region.
	NewPeerIds       []uint64 `protobuf:"varint,3,rep,name=new_peer_ids" json:"new_peer_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SplitRequest) Reset()                    { *m = SplitRequest{} }
func (m *SplitRequest) String() string            { return proto.CompactTextString(m) }
func (*SplitRequest) ProtoMessage()               {}
func (*SplitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *SplitRequest) GetSplitKey() []byte {
	if m != nil {
		return m.SplitKey
	}
	return nil
}

func (m *SplitRequest) GetNewRegionId() uint64 {
	if m != nil && m.NewRegionId != nil {
		return *m.NewRegionId
	}
	return 0
}

func (m *SplitRequest) GetNewPeerIds() []uint64 {
	if m != nil {
		return m.NewPeerIds
	}
	return nil
}

type SplitResponse struct {
	Left             *metapb.Region `protobuf:"bytes,1,opt,name=left" json:"left,omitempty"`
	Right            *metapb.Region `protobuf:"bytes,2,opt,name=right" json:"right,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SplitResponse) Reset()                    { *m = SplitResponse{} }
func (m *SplitResponse) String() string            { return proto.CompactTextString(m) }
func (*SplitResponse) ProtoMessage()               {}
func (*SplitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *SplitResponse) GetLeft() *metapb.Region {
	if m != nil {
		return m.Left
	}
	return nil
}

func (m *SplitResponse) GetRight() *metapb.Region {
	if m != nil {
		return m.Right
	}
	return nil
}

type CompactLogRequest struct {
	CompactIndex     *uint64 `protobuf:"varint,1,opt,name=compact_index" json:"compact_index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CompactLogRequest) Reset()                    { *m = CompactLogRequest{} }
func (m *CompactLogRequest) String() string            { return proto.CompactTextString(m) }
func (*CompactLogRequest) ProtoMessage()               {}
func (*CompactLogRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CompactLogRequest) GetCompactIndex() uint64 {
	if m != nil && m.CompactIndex != nil {
		return *m.CompactIndex
	}
	return 0
}

type CompactLogResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CompactLogResponse) Reset()                    { *m = CompactLogResponse{} }
func (m *CompactLogResponse) String() string            { return proto.CompactTextString(m) }
func (*CompactLogResponse) ProtoMessage()               {}
func (*CompactLogResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type AdminRequest struct {
	CmdType          *AdminCommandType  `protobuf:"varint,1,opt,name=cmd_type,enum=raft_cmdpb.AdminCommandType" json:"cmd_type,omitempty"`
	ChangePeer       *ChangePeerRequest `protobuf:"bytes,2,opt,name=change_peer" json:"change_peer,omitempty"`
	Split            *SplitRequest      `protobuf:"bytes,3,opt,name=split" json:"split,omitempty"`
	CompactLog       *CompactLogRequest `protobuf:"bytes,4,opt,name=compact_log" json:"compact_log,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *AdminRequest) Reset()                    { *m = AdminRequest{} }
func (m *AdminRequest) String() string            { return proto.CompactTextString(m) }
func (*AdminRequest) ProtoMessage()               {}
func (*AdminRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *AdminRequest) GetCmdType() AdminCommandType {
	if m != nil && m.CmdType != nil {
		return *m.CmdType
	}
	return AdminCommandType_InvalidAdmin
}

func (m *AdminRequest) GetChangePeer() *ChangePeerRequest {
	if m != nil {
		return m.ChangePeer
	}
	return nil
}

func (m *AdminRequest) GetSplit() *SplitRequest {
	if m != nil {
		return m.Split
	}
	return nil
}

func (m *AdminRequest) GetCompactLog() *CompactLogRequest {
	if m != nil {
		return m.CompactLog
	}
	return nil
}

type AdminResponse struct {
	CmdType          *AdminCommandType   `protobuf:"varint,1,opt,name=cmd_type,enum=raft_cmdpb.AdminCommandType" json:"cmd_type,omitempty"`
	ChangePeer       *ChangePeerResponse `protobuf:"bytes,2,opt,name=change_peer" json:"change_peer,omitempty"`
	Split            *SplitResponse      `protobuf:"bytes,3,opt,name=split" json:"split,omitempty"`
	CompactLog       *CompactLogResponse `protobuf:"bytes,4,opt,name=compact_log" json:"compact_log,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *AdminResponse) Reset()                    { *m = AdminResponse{} }
func (m *AdminResponse) String() string            { return proto.CompactTextString(m) }
func (*AdminResponse) ProtoMessage()               {}
func (*AdminResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *AdminResponse) GetCmdType() AdminCommandType {
	if m != nil && m.CmdType != nil {
		return *m.CmdType
	}
	return AdminCommandType_InvalidAdmin
}

func (m *AdminResponse) GetChangePeer() *ChangePeerResponse {
	if m != nil {
		return m.ChangePeer
	}
	return nil
}

func (m *AdminResponse) GetSplit() *SplitResponse {
	if m != nil {
		return m.Split
	}
	return nil
}

func (m *AdminResponse) GetCompactLog() *CompactLogResponse {
	if m != nil {
		return m.CompactLog
	}
	return nil
}

// For get the leader of the region.
type RegionLeaderRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RegionLeaderRequest) Reset()                    { *m = RegionLeaderRequest{} }
func (m *RegionLeaderRequest) String() string            { return proto.CompactTextString(m) }
func (*RegionLeaderRequest) ProtoMessage()               {}
func (*RegionLeaderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type RegionLeaderResponse struct {
	Leader           *metapb.Peer `protobuf:"bytes,1,opt,name=leader" json:"leader,omitempty"`
	CurrentTerm      *uint64      `protobuf:"varint,2,opt,name=current_term" json:"current_term,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RegionLeaderResponse) Reset()                    { *m = RegionLeaderResponse{} }
func (m *RegionLeaderResponse) String() string            { return proto.CompactTextString(m) }
func (*RegionLeaderResponse) ProtoMessage()               {}
func (*RegionLeaderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *RegionLeaderResponse) GetLeader() *metapb.Peer {
	if m != nil {
		return m.Leader
	}
	return nil
}

func (m *RegionLeaderResponse) GetCurrentTerm() uint64 {
	if m != nil && m.CurrentTerm != nil {
		return *m.CurrentTerm
	}
	return 0
}

// For getting more information of the region.
// We add some admin operations (ChangePeer, Split...) into the pb job list,
// then pd server will peek the first one, handle it and then pop it from the job lib.
// But sometimes, the pd server may crash before popping. When another pd server
// starts and finds the job is running but not finished, it will first check whether
// the raft server already has handled this job.
// E,g, for ChangePeer, if we add Peer10 into region1 and find region1 has already had
// Peer10, we can think this ChangePeer is finished, and can pop this job from job list
// directly.
type RegionDetailRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RegionDetailRequest) Reset()                    { *m = RegionDetailRequest{} }
func (m *RegionDetailRequest) String() string            { return proto.CompactTextString(m) }
func (*RegionDetailRequest) ProtoMessage()               {}
func (*RegionDetailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type RegionDetailResponse struct {
	Region           *metapb.Region `protobuf:"bytes,1,opt,name=region" json:"region,omitempty"`
	Leader           *metapb.Peer   `protobuf:"bytes,2,opt,name=leader" json:"leader,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *RegionDetailResponse) Reset()                    { *m = RegionDetailResponse{} }
func (m *RegionDetailResponse) String() string            { return proto.CompactTextString(m) }
func (*RegionDetailResponse) ProtoMessage()               {}
func (*RegionDetailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *RegionDetailResponse) GetRegion() *metapb.Region {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *RegionDetailResponse) GetLeader() *metapb.Peer {
	if m != nil {
		return m.Leader
	}
	return nil
}

type StatusRequest struct {
	CmdType          *StatusCommandType   `protobuf:"varint,1,opt,name=cmd_type,enum=raft_cmdpb.StatusCommandType" json:"cmd_type,omitempty"`
	RegionLeader     *RegionLeaderRequest `protobuf:"bytes,2,opt,name=region_leader" json:"region_leader,omitempty"`
	RegionDetail     *RegionDetailRequest `protobuf:"bytes,3,opt,name=region_detail" json:"region_detail,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *StatusRequest) GetCmdType() StatusCommandType {
	if m != nil && m.CmdType != nil {
		return *m.CmdType
	}
	return StatusCommandType_InvalidStatus
}

func (m *StatusRequest) GetRegionLeader() *RegionLeaderRequest {
	if m != nil {
		return m.RegionLeader
	}
	return nil
}

func (m *StatusRequest) GetRegionDetail() *RegionDetailRequest {
	if m != nil {
		return m.RegionDetail
	}
	return nil
}

type StatusResponse struct {
	CmdType          *StatusCommandType    `protobuf:"varint,1,opt,name=cmd_type,enum=raft_cmdpb.StatusCommandType" json:"cmd_type,omitempty"`
	RegionLeader     *RegionLeaderResponse `protobuf:"bytes,2,opt,name=region_leader" json:"region_leader,omitempty"`
	RegionDetail     *RegionDetailResponse `protobuf:"bytes,3,opt,name=region_detail" json:"region_detail,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *StatusResponse) GetCmdType() StatusCommandType {
	if m != nil && m.CmdType != nil {
		return *m.CmdType
	}
	return StatusCommandType_InvalidStatus
}

func (m *StatusResponse) GetRegionLeader() *RegionLeaderResponse {
	if m != nil {
		return m.RegionLeader
	}
	return nil
}

func (m *StatusResponse) GetRegionDetail() *RegionDetailResponse {
	if m != nil {
		return m.RegionDetail
	}
	return nil
}

type RaftRequestHeader struct {
	RegionId *uint64      `protobuf:"varint,1,opt,name=region_id" json:"region_id,omitempty"`
	Peer     *metapb.Peer `protobuf:"bytes,2,opt,name=peer" json:"peer,omitempty"`
	// true for read linearization
	ReadQuorum *bool `protobuf:"varint,3,opt,name=read_quorum" json:"read_quorum,omitempty"`
	// 16 bytes, to distinguish request.
	Uuid             []byte `protobuf:"bytes,4,opt,name=uuid" json:"uuid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RaftRequestHeader) Reset()                    { *m = RaftRequestHeader{} }
func (m *RaftRequestHeader) String() string            { return proto.CompactTextString(m) }
func (*RaftRequestHeader) ProtoMessage()               {}
func (*RaftRequestHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *RaftRequestHeader) GetRegionId() uint64 {
	if m != nil && m.RegionId != nil {
		return *m.RegionId
	}
	return 0
}

func (m *RaftRequestHeader) GetPeer() *metapb.Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *RaftRequestHeader) GetReadQuorum() bool {
	if m != nil && m.ReadQuorum != nil {
		return *m.ReadQuorum
	}
	return false
}

func (m *RaftRequestHeader) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

type RaftResponseHeader struct {
	Error            *errorpb.Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Uuid             []byte         `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
	CurrentTerm      *uint64        `protobuf:"varint,3,opt,name=current_term" json:"current_term,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *RaftResponseHeader) Reset()                    { *m = RaftResponseHeader{} }
func (m *RaftResponseHeader) String() string            { return proto.CompactTextString(m) }
func (*RaftResponseHeader) ProtoMessage()               {}
func (*RaftResponseHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *RaftResponseHeader) GetError() *errorpb.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *RaftResponseHeader) GetUuid() []byte {
	if m != nil {
		return m.Uuid
	}
	return nil
}

func (m *RaftResponseHeader) GetCurrentTerm() uint64 {
	if m != nil && m.CurrentTerm != nil {
		return *m.CurrentTerm
	}
	return 0
}

type RaftCommandRequest struct {
	Header *RaftRequestHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	// We can't enclose normal requests and administrator request
	// at same time.
	Requests         []*Request     `protobuf:"bytes,2,rep,name=requests" json:"requests,omitempty"`
	AdminRequest     *AdminRequest  `protobuf:"bytes,3,opt,name=admin_request" json:"admin_request,omitempty"`
	StatusRequest    *StatusRequest `protobuf:"bytes,4,opt,name=status_request" json:"status_request,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *RaftCommandRequest) Reset()                    { *m = RaftCommandRequest{} }
func (m *RaftCommandRequest) String() string            { return proto.CompactTextString(m) }
func (*RaftCommandRequest) ProtoMessage()               {}
func (*RaftCommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *RaftCommandRequest) GetHeader() *RaftRequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RaftCommandRequest) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *RaftCommandRequest) GetAdminRequest() *AdminRequest {
	if m != nil {
		return m.AdminRequest
	}
	return nil
}

func (m *RaftCommandRequest) GetStatusRequest() *StatusRequest {
	if m != nil {
		return m.StatusRequest
	}
	return nil
}

type RaftCommandResponse struct {
	Header           *RaftResponseHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Responses        []*Response         `protobuf:"bytes,2,rep,name=responses" json:"responses,omitempty"`
	AdminResponse    *AdminResponse      `protobuf:"bytes,3,opt,name=admin_response" json:"admin_response,omitempty"`
	StatusResponse   *StatusResponse     `protobuf:"bytes,4,opt,name=status_response" json:"status_response,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *RaftCommandResponse) Reset()                    { *m = RaftCommandResponse{} }
func (m *RaftCommandResponse) String() string            { return proto.CompactTextString(m) }
func (*RaftCommandResponse) ProtoMessage()               {}
func (*RaftCommandResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *RaftCommandResponse) GetHeader() *RaftResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *RaftCommandResponse) GetResponses() []*Response {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (m *RaftCommandResponse) GetAdminResponse() *AdminResponse {
	if m != nil {
		return m.AdminResponse
	}
	return nil
}

func (m *RaftCommandResponse) GetStatusResponse() *StatusResponse {
	if m != nil {
		return m.StatusResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "raft_cmdpb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "raft_cmdpb.GetResponse")
	proto.RegisterType((*SeekRequest)(nil), "raft_cmdpb.SeekRequest")
	proto.RegisterType((*SeekResponse)(nil), "raft_cmdpb.SeekResponse")
	proto.RegisterType((*PutRequest)(nil), "raft_cmdpb.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "raft_cmdpb.PutResponse")
	proto.RegisterType((*DeleteRequest)(nil), "raft_cmdpb.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "raft_cmdpb.DeleteResponse")
	proto.RegisterType((*Request)(nil), "raft_cmdpb.Request")
	proto.RegisterType((*Response)(nil), "raft_cmdpb.Response")
	proto.RegisterType((*ChangePeerRequest)(nil), "raft_cmdpb.ChangePeerRequest")
	proto.RegisterType((*ChangePeerResponse)(nil), "raft_cmdpb.ChangePeerResponse")
	proto.RegisterType((*SplitRequest)(nil), "raft_cmdpb.SplitRequest")
	proto.RegisterType((*SplitResponse)(nil), "raft_cmdpb.SplitResponse")
	proto.RegisterType((*CompactLogRequest)(nil), "raft_cmdpb.CompactLogRequest")
	proto.RegisterType((*CompactLogResponse)(nil), "raft_cmdpb.CompactLogResponse")
	proto.RegisterType((*AdminRequest)(nil), "raft_cmdpb.AdminRequest")
	proto.RegisterType((*AdminResponse)(nil), "raft_cmdpb.AdminResponse")
	proto.RegisterType((*RegionLeaderRequest)(nil), "raft_cmdpb.RegionLeaderRequest")
	proto.RegisterType((*RegionLeaderResponse)(nil), "raft_cmdpb.RegionLeaderResponse")
	proto.RegisterType((*RegionDetailRequest)(nil), "raft_cmdpb.RegionDetailRequest")
	proto.RegisterType((*RegionDetailResponse)(nil), "raft_cmdpb.RegionDetailResponse")
	proto.RegisterType((*StatusRequest)(nil), "raft_cmdpb.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "raft_cmdpb.StatusResponse")
	proto.RegisterType((*RaftRequestHeader)(nil), "raft_cmdpb.RaftRequestHeader")
	proto.RegisterType((*RaftResponseHeader)(nil), "raft_cmdpb.RaftResponseHeader")
	proto.RegisterType((*RaftCommandRequest)(nil), "raft_cmdpb.RaftCommandRequest")
	proto.RegisterType((*RaftCommandResponse)(nil), "raft_cmdpb.RaftCommandResponse")
	proto.RegisterEnum("raft_cmdpb.CommandType", CommandType_name, CommandType_value)
	proto.RegisterEnum("raft_cmdpb.AdminCommandType", AdminCommandType_name, AdminCommandType_value)
	proto.RegisterEnum("raft_cmdpb.StatusCommandType", StatusCommandType_name, StatusCommandType_value)
}

var fileDescriptor0 = []byte{
	// 982 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x56, 0xeb, 0x6e, 0xdc, 0x44,
	0x14, 0xc6, 0xb1, 0x77, 0xb3, 0x3d, 0xb6, 0x17, 0xaf, 0x93, 0x92, 0xcd, 0x2a, 0x09, 0x91, 0x69,
	0x69, 0xba, 0x88, 0x20, 0x12, 0x44, 0x7f, 0x43, 0x8b, 0x80, 0x2a, 0x82, 0x2a, 0xad, 0xc4, 0x4f,
	0xcb, 0xac, 0x27, 0x1b, 0xab, 0xeb, 0x4b, 0x7d, 0x01, 0x22, 0xf1, 0x50, 0x48, 0xbc, 0x07, 0x20,
	0x21, 0x78, 0x1e, 0xc6, 0x33, 0x67, 0xbc, 0x33, 0xf1, 0x2c, 0x6a, 0x7e, 0xad, 0x7c, 0x2e, 0xdf,
	0x39, 0xdf, 0xb9, 0xed, 0x80, 0x57, 0x46, 0x57, 0x75, 0xb8, 0x48, 0xe3, 0xe2, 0xc7, 0xd3, 0xa2,
	0xcc, 0xeb, 0xdc, 0x87, 0xb5, 0x64, 0xe6, 0xa4, 0xa4, 0x8e, 0x84, 0x66, 0xe6, 0x92, 0xb2, 0xcc,
	0xcb, 0xee, 0xd3, 0x69, 0x0d, 0xc5, 0x57, 0xb0, 0x0f, 0xf0, 0x35, 0xa9, 0x2f, 0xc9, 0x9b, 0x86,
	0x54, 0xb5, 0x6f, 0x83, 0xf9, 0x9a, 0xdc, 0x4c, 0x8d, 0x63, 0xe3, 0xc4, 0x09, 0x0e, 0xc0, 0x66,
	0xaa, 0xaa, 0xc8, 0xb3, 0x8a, 0xf8, 0x2e, 0x0c, 0x7e, 0x8a, 0x56, 0x0d, 0x41, 0xed, 0x0c, 0xec,
	0x97, 0x84, 0xbc, 0xd6, 0x7a, 0xce, 0xc1, 0xe1, 0x3a, 0x74, 0x95, 0x95, 0x6b, 0x9c, 0x2d, 0x66,
	0x7b, 0x02, 0xf0, 0xa2, 0xd1, 0x26, 0x70, 0xdb, 0xd2, 0x05, 0x9b, 0x59, 0x72, 0x50, 0x9a, 0x9e,
	0xfb, 0x8c, 0xac, 0x48, 0x4d, 0xb4, 0x29, 0x78, 0x30, 0x16, 0x5a, 0xb4, 0xff, 0xcb, 0x80, 0x6d,
	0x61, 0xfa, 0x18, 0x46, 0xb4, 0x52, 0x61, 0x7d, 0x53, 0x70, 0x3a, 0xe3, 0xb3, 0xbd, 0x53, 0xa9,
	0xa2, 0x4f, 0xf3, 0x34, 0x8d, 0xb2, 0xf8, 0x15, 0x55, 0xfb, 0x1f, 0x80, 0xb9, 0x24, 0x35, 0x4b,
	0xc1, 0x3e, 0x7b, 0x4f, 0xb6, 0x92, 0xea, 0xf6, 0x10, 0xac, 0x8a, 0x12, 0x9e, 0x9a, 0xcc, 0x4a,
	0xc1, 0x92, 0x8b, 0x44, 0xb1, 0x8a, 0xa6, 0x9e, 0x5a, 0x7d, 0x2c, 0xa9, 0x04, 0x8f, 0x61, 0x18,
	0xb3, 0xcc, 0xa7, 0x03, 0x66, 0xb7, 0x2f, 0xdb, 0x29, 0x8c, 0x83, 0x7f, 0x0c, 0x18, 0x75, 0x45,
	0xbe, 0x03, 0xa7, 0x07, 0x32, 0xa7, 0xbd, 0x1e, 0x27, 0x04, 0xfc, 0x50, 0x21, 0x35, 0xed, 0x93,
	0x42, 0xbb, 0x07, 0x32, 0xab, 0xbd, 0x1e, 0x2b, 0xb4, 0x9a, 0xdf, 0xa2, 0x35, 0xd3, 0xd1, 0xc2,
	0x56, 0xfd, 0x0a, 0x93, 0xa7, 0xd7, 0x51, 0xb6, 0x24, 0x2f, 0x08, 0x29, 0x45, 0x5d, 0x3e, 0x02,
	0x7b, 0xc1, 0x84, 0x32, 0x45, 0x5e, 0x44, 0x46, 0x2f, 0xbb, 0xe2, 0x3e, 0x8c, 0xe1, 0x0c, 0xac,
	0x82, 0xfa, 0x22, 0x45, 0xe7, 0x14, 0x17, 0xa2, 0xc5, 0xf3, 0x8f, 0x60, 0x58, 0x92, 0x65, 0x92,
	0x67, 0xc8, 0x6c, 0x2c, 0xb4, 0x97, 0x4c, 0x1a, 0x7c, 0x06, 0xbe, 0x1c, 0x1d, 0xf3, 0x5f, 0x7b,
	0x19, 0x5a, 0xaf, 0xef, 0xe8, 0xcc, 0x17, 0xab, 0xa4, 0x6b, 0xe3, 0x04, 0xee, 0x55, 0xed, 0x77,
	0xb8, 0x9e, 0xe7, 0xfb, 0xe0, 0x66, 0xe4, 0xe7, 0x90, 0xc3, 0x84, 0x49, 0xcc, 0xb2, 0xb3, 0xfc,
	0x5d, 0x70, 0x5a, 0x71, 0x9b, 0x2f, 0x15, 0x56, 0x34, 0x2b, 0xf3, 0xc4, 0x0a, 0x2e, 0xc0, 0x45,
	0x3c, 0x4c, 0xe0, 0x00, 0xac, 0x15, 0xb9, 0xaa, 0xf5, 0xe1, 0xfd, 0x43, 0x18, 0x94, 0xc9, 0xf2,
	0x5a, 0x34, 0xf5, 0x76, 0x76, 0x73, 0x5a, 0xd1, 0x3c, 0x2d, 0xa2, 0x45, 0x7d, 0x91, 0x2f, 0x45,
	0x8a, 0x34, 0x9f, 0x05, 0x17, 0x86, 0x49, 0x16, 0x93, 0x5f, 0x18, 0xb4, 0x15, 0xec, 0x52, 0xfe,
	0x92, 0x2d, 0xf6, 0xe4, 0x4f, 0x03, 0x9c, 0x2f, 0xe2, 0x34, 0xc9, 0x84, 0xf7, 0x69, 0x6f, 0xde,
	0x0e, 0xe4, 0x96, 0x32, 0x5b, 0x79, 0xe8, 0xce, 0xba, 0xfe, 0x49, 0x9d, 0x39, 0x54, 0x46, 0xb4,
	0xd7, 0xf3, 0x47, 0x30, 0x60, 0x45, 0xd4, 0xce, 0xa0, 0x5c, 0xed, 0x16, 0x1c, 0xa9, 0xac, 0xf2,
	0x25, 0xce, 0xe2, 0xe1, 0xad, 0xf9, 0x57, 0xe9, 0x07, 0x7f, 0x1b, 0xe0, 0x22, 0x23, 0x2c, 0xf1,
	0x5d, 0x29, 0x9d, 0xeb, 0x28, 0x1d, 0x6d, 0xa2, 0x84, 0x41, 0x4e, 0x54, 0x4e, 0xfb, 0x1a, 0x4e,
	0x68, 0x79, 0xae, 0x23, 0x75, 0xb4, 0x89, 0x14, 0xf6, 0xe9, 0x3e, 0xec, 0xf0, 0x9e, 0x5f, 0x90,
	0x28, 0xee, 0x2a, 0x19, 0x3c, 0x87, 0x5d, 0x55, 0xdc, 0x4d, 0xd5, 0x70, 0xc5, 0x24, 0x38, 0x57,
	0xea, 0xaa, 0xd0, 0xd1, 0x5c, 0x34, 0x65, 0x49, 0xb2, 0x3a, 0xac, 0x49, 0x99, 0xf2, 0x81, 0x5d,
	0x87, 0x78, 0x46, 0x4d, 0x93, 0x95, 0x08, 0xf1, 0x4a, 0x84, 0x10, 0xe2, 0xb7, 0xdb, 0x1c, 0x29,
	0x05, 0xcd, 0xb6, 0x06, 0xbf, 0xd1, 0x2e, 0xbd, 0xac, 0xa3, 0xba, 0xa9, 0x44, 0xaf, 0x3f, 0xe9,
	0x75, 0x49, 0x69, 0x34, 0x37, 0x96, 0xdb, 0xf4, 0x39, 0xb8, 0xb8, 0x73, 0x4a, 0x9c, 0xf7, 0x65,
	0x2f, 0x4d, 0xcd, 0x24, 0xbf, 0x98, 0x31, 0xc2, 0x8e, 0x69, 0xfc, 0xd4, 0x42, 0xfc, 0x6e, 0xc0,
	0x58, 0xa4, 0x8c, 0x35, 0xb8, 0x73, 0xce, 0x4f, 0xf4, 0x39, 0x1f, 0x6f, 0xce, 0x19, 0x23, 0x3d,
	0xd1, 0x27, 0x7d, 0xbc, 0x39, 0x69, 0x1c, 0x1c, 0x02, 0x93, 0x4b, 0x6a, 0x82, 0x24, 0xbe, 0x61,
	0xa8, 0xed, 0x15, 0x5b, 0x9f, 0x2b, 0x76, 0x1e, 0xfe, 0xf7, 0xb4, 0xee, 0x80, 0x5d, 0x52, 0xc7,
	0xf0, 0x4d, 0x93, 0x97, 0x4d, 0xca, 0x42, 0x8f, 0x7c, 0x07, 0xac, 0xa6, 0xa1, 0xee, 0x16, 0xfb,
	0x63, 0xfe, 0x01, 0x7c, 0x1e, 0x86, 0x87, 0xc5, 0x38, 0xf4, 0x7c, 0xb1, 0x57, 0x4a, 0x37, 0x22,
	0xe2, 0xcd, 0xf2, 0x55, 0xfb, 0xdb, 0x41, 0xb0, 0x87, 0x40, 0x6f, 0x2a, 0x4d, 0x36, 0x95, 0x7f,
	0x18, 0x1c, 0x19, 0xab, 0x28, 0x9a, 0xf8, 0x31, 0x0c, 0xaf, 0xe5, 0x01, 0x57, 0xea, 0xde, 0x27,
	0xfc, 0x10, 0x46, 0x25, 0x17, 0x54, 0x34, 0x9a, 0x49, 0x1d, 0x76, 0xd4, 0xca, 0x89, 0x19, 0x74,
	0xa3, 0xf6, 0x1a, 0x84, 0x68, 0xac, 0x3b, 0x50, 0xca, 0xb5, 0xfc, 0x14, 0xc6, 0x15, 0x6b, 0x72,
	0xe7, 0x61, 0x69, 0xd6, 0x5f, 0x9e, 0xf3, 0xe0, 0x5f, 0x83, 0xee, 0x99, 0x4c, 0xa8, 0xbb, 0x52,
	0x2a, 0xa3, 0xa3, 0x3e, 0x23, 0xa5, 0xb6, 0x8f, 0xda, 0x1e, 0x72, 0x89, 0xe0, 0xb4, 0xab, 0x72,
	0x42, 0x60, 0x9a, 0xa3, 0x20, 0xc5, 0x25, 0xba, 0x13, 0xa5, 0x5e, 0xcc, 0x73, 0x78, 0xb7, 0xa3,
	0x85, 0x3e, 0x56, 0xff, 0xef, 0x5d, 0x5d, 0x86, 0xf9, 0x97, 0x60, 0xcb, 0xa3, 0x6e, 0xc3, 0xf6,
	0xb7, 0x19, 0x7d, 0xe8, 0x25, 0xb1, 0xf7, 0x8e, 0xbf, 0x0d, 0x26, 0x7d, 0x83, 0x78, 0x86, 0x3f,
	0x02, 0xab, 0x7d, 0x65, 0x78, 0x5b, 0xad, 0x88, 0x3e, 0x24, 0x3c, 0xd3, 0x07, 0x18, 0xf2, 0x87,
	0x82, 0x67, 0xcd, 0xbf, 0x07, 0xaf, 0x77, 0x8e, 0x3d, 0x70, 0x10, 0x88, 0xa9, 0x28, 0xda, 0x18,
	0x60, 0x7d, 0x81, 0x29, 0xe8, 0x3d, 0x18, 0xb0, 0x13, 0x4b, 0x51, 0x5b, 0x55, 0x77, 0x3d, 0x3d,
	0x73, 0xfe, 0x1c, 0x26, 0xfd, 0x2d, 0x9c, 0x80, 0x8b, 0x88, 0x5c, 0x47, 0x21, 0x69, 0x10, 0x79,
	0xef, 0x28, 0x68, 0x27, 0xe1, 0x0b, 0xe5, 0x6d, 0xfd, 0x17, 0x00, 0x00, 0xff, 0xff, 0x20, 0xae,
	0x72, 0x53, 0x9e, 0x0b, 0x00, 0x00,
}
