// Code generated by protoc-gen-go.
// source: metapb.proto
// DO NOT EDIT!

/*
Package metapb is a generated protocol buffer package.

It is generated from these files:
	metapb.proto

It has these top-level messages:
	Cluster
	Node
	Store
	RegionEpoch
	Peer
	Region
*/
package metapb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Cluster struct {
	ClusterId *uint64 `protobuf:"varint,1,opt,name=cluster_id" json:"cluster_id,omitempty"`
	// max peer number for a region.
	// pd will do the auto-balance if region peer number mismatches.
	MaxPeerNumber    *uint32 `protobuf:"varint,2,opt,name=max_peer_number" json:"max_peer_number,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Cluster) Reset()                    { *m = Cluster{} }
func (m *Cluster) String() string            { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()               {}
func (*Cluster) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Cluster) GetClusterId() uint64 {
	if m != nil && m.ClusterId != nil {
		return *m.ClusterId
	}
	return 0
}

func (m *Cluster) GetMaxPeerNumber() uint32 {
	if m != nil && m.MaxPeerNumber != nil {
		return *m.MaxPeerNumber
	}
	return 0
}

type Node struct {
	NodeId *uint64 `protobuf:"varint,1,opt,name=node_id" json:"node_id,omitempty"`
	// Address for communication between nodes.
	Address *string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	// Address for communication between client and node.
	ClientAddr       *string `protobuf:"bytes,3,opt,name=client_addr" json:"client_addr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Node) GetNodeId() uint64 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *Node) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *Node) GetClientAddr() string {
	if m != nil && m.ClientAddr != nil {
		return *m.ClientAddr
	}
	return ""
}

type Store struct {
	StoreId          *uint64 `protobuf:"varint,1,opt,name=store_id" json:"store_id,omitempty"`
	NodeId           *uint64 `protobuf:"varint,2,opt,name=node_id" json:"node_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Store) Reset()                    { *m = Store{} }
func (m *Store) String() string            { return proto.CompactTextString(m) }
func (*Store) ProtoMessage()               {}
func (*Store) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Store) GetStoreId() uint64 {
	if m != nil && m.StoreId != nil {
		return *m.StoreId
	}
	return 0
}

func (m *Store) GetNodeId() uint64 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

type RegionEpoch struct {
	// Conf change version, auto increment when add or remove peer
	ConfVer *uint64 `protobuf:"varint,1,opt,name=conf_ver" json:"conf_ver,omitempty"`
	// Region version, auto increment when split or merge
	Version          *uint64 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RegionEpoch) Reset()                    { *m = RegionEpoch{} }
func (m *RegionEpoch) String() string            { return proto.CompactTextString(m) }
func (*RegionEpoch) ProtoMessage()               {}
func (*RegionEpoch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RegionEpoch) GetConfVer() uint64 {
	if m != nil && m.ConfVer != nil {
		return *m.ConfVer
	}
	return 0
}

func (m *RegionEpoch) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type Peer struct {
	PeerId           *uint64 `protobuf:"varint,1,opt,name=peer_id" json:"peer_id,omitempty"`
	NodeId           *uint64 `protobuf:"varint,2,opt,name=node_id" json:"node_id,omitempty"`
	StoreId          *uint64 `protobuf:"varint,3,opt,name=store_id" json:"store_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Peer) Reset()                    { *m = Peer{} }
func (m *Peer) String() string            { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()               {}
func (*Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Peer) GetPeerId() uint64 {
	if m != nil && m.PeerId != nil {
		return *m.PeerId
	}
	return 0
}

func (m *Peer) GetNodeId() uint64 {
	if m != nil && m.NodeId != nil {
		return *m.NodeId
	}
	return 0
}

func (m *Peer) GetStoreId() uint64 {
	if m != nil && m.StoreId != nil {
		return *m.StoreId
	}
	return 0
}

type Region struct {
	RegionId *uint64 `protobuf:"varint,1,opt,name=region_id" json:"region_id,omitempty"`
	// Region key range [start_key, end_key).
	StartKey         []byte       `protobuf:"bytes,2,opt,name=start_key" json:"start_key,omitempty"`
	EndKey           []byte       `protobuf:"bytes,3,opt,name=end_key" json:"end_key,omitempty"`
	RegionEpoch      *RegionEpoch `protobuf:"bytes,4,opt,name=region_epoch" json:"region_epoch,omitempty"`
	Peers            []*Peer      `protobuf:"bytes,5,rep,name=peers" json:"peers,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Region) Reset()                    { *m = Region{} }
func (m *Region) String() string            { return proto.CompactTextString(m) }
func (*Region) ProtoMessage()               {}
func (*Region) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Region) GetRegionId() uint64 {
	if m != nil && m.RegionId != nil {
		return *m.RegionId
	}
	return 0
}

func (m *Region) GetStartKey() []byte {
	if m != nil {
		return m.StartKey
	}
	return nil
}

func (m *Region) GetEndKey() []byte {
	if m != nil {
		return m.EndKey
	}
	return nil
}

func (m *Region) GetRegionEpoch() *RegionEpoch {
	if m != nil {
		return m.RegionEpoch
	}
	return nil
}

func (m *Region) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*Cluster)(nil), "metapb.Cluster")
	proto.RegisterType((*Node)(nil), "metapb.Node")
	proto.RegisterType((*Store)(nil), "metapb.Store")
	proto.RegisterType((*RegionEpoch)(nil), "metapb.RegionEpoch")
	proto.RegisterType((*Peer)(nil), "metapb.Peer")
	proto.RegisterType((*Region)(nil), "metapb.Region")
}

var fileDescriptor0 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0x92, 0xb4, 0xf4, 0x12, 0x54, 0x70, 0x07, 0x22, 0xb1, 0x54, 0x99, 0x80, 0xa1,
	0x42, 0x0c, 0x0c, 0x48, 0x4c, 0x88, 0x15, 0x21, 0xf8, 0x01, 0x56, 0x1a, 0x1f, 0x10, 0xd1, 0xd8,
	0x91, 0xed, 0x22, 0xf8, 0x05, 0xfc, 0x6d, 0xee, 0x9c, 0x94, 0xd2, 0xa1, 0x53, 0xce, 0x9f, 0xdf,
	0x7b, 0xf7, 0x62, 0xc8, 0x5b, 0xf4, 0x55, 0xb7, 0x5c, 0x74, 0xd6, 0x78, 0x23, 0x46, 0xfd, 0xa9,
	0xbc, 0x81, 0xf1, 0xfd, 0x6a, 0xed, 0x3c, 0x5a, 0x21, 0x00, 0xea, 0x7e, 0x94, 0x8d, 0x2a, 0xa2,
	0x79, 0x74, 0x9e, 0x88, 0x53, 0x98, 0xb6, 0xd5, 0x97, 0xec, 0x90, 0xa0, 0x5e, 0xb7, 0x4b, 0xb4,
	0xc5, 0x01, 0x5d, 0x1c, 0x95, 0x77, 0x90, 0x3c, 0x1a, 0x85, 0x62, 0x0a, 0x63, 0x4d, 0xdf, 0xad,
	0x83, 0x40, 0xa5, 0x94, 0x45, 0xe7, 0x82, 0x72, 0x22, 0x66, 0x90, 0xd5, 0xab, 0x06, 0xb5, 0x97,
	0xcc, 0x8b, 0x98, 0x61, 0x79, 0x09, 0xe9, 0x8b, 0x37, 0x16, 0xc5, 0x31, 0x1c, 0x3a, 0x1e, 0x76,
	0x02, 0x36, 0x89, 0x1c, 0x90, 0x94, 0x57, 0x90, 0x3d, 0xe3, 0x5b, 0x63, 0xf4, 0x43, 0x67, 0xea,
	0x77, 0x76, 0xd4, 0x46, 0xbf, 0xca, 0x4f, 0xea, 0xf2, 0xe7, 0xa0, 0x83, 0x23, 0xc5, 0xe0, 0xb8,
	0x85, 0xe4, 0x89, 0x1a, 0xf3, 0x45, 0x68, 0xbe, 0x37, 0x7b, 0x67, 0x7d, 0x1c, 0xbc, 0x3f, 0x11,
	0x8c, 0xfa, 0x75, 0xe2, 0x04, 0x26, 0x36, 0x4c, 0xdb, 0x00, 0x42, 0xce, 0x57, 0xd6, 0xcb, 0x0f,
	0xfc, 0x0e, 0x11, 0x39, 0x67, 0xa2, 0x56, 0x01, 0xc4, 0x01, 0x5c, 0x40, 0x3e, 0xd8, 0x90, 0x0b,
	0x17, 0x09, 0xd1, 0xec, 0x7a, 0xb6, 0x18, 0xde, 0xff, 0xff, 0xbf, 0x9c, 0x41, 0xca, 0x05, 0x5d,
	0x91, 0xce, 0x63, 0xd2, 0xe4, 0x1b, 0x0d, 0xb7, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x23, 0xb5,
	0x14, 0xfb, 0xb1, 0x01, 0x00, 0x00,
}
