// Code generated by protoc-gen-go.
// source: msgpb.proto
// DO NOT EDIT!

/*
Package msgpb is a generated protocol buffer package.

It is generated from these files:
	msgpb.proto

It has these top-level messages:
	Message
*/
package msgpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import raft_cmdpb "github.com/pingcap/kvproto/pkg/raft_cmdpb"
import raft_serverpb "github.com/pingcap/kvproto/pkg/raft_serverpb"
import kvrpcpb "github.com/pingcap/kvproto/pkg/kvrpcpb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type MessageType int32

const (
	MessageType_None    MessageType = 0
	MessageType_Cmd     MessageType = 1
	MessageType_CmdResp MessageType = 2
	MessageType_Raft    MessageType = 3
	MessageType_KvReq   MessageType = 4
	MessageType_KvResp  MessageType = 5
)

var MessageType_name = map[int32]string{
	0: "None",
	1: "Cmd",
	2: "CmdResp",
	3: "Raft",
	4: "KvReq",
	5: "KvResp",
}
var MessageType_value = map[string]int32{
	"None":    0,
	"Cmd":     1,
	"CmdResp": 2,
	"Raft":    3,
	"KvReq":   4,
	"KvResp":  5,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Message holds all messages communicating with TiKV.
type Message struct {
	MsgType          *MessageType                `protobuf:"varint,1,opt,name=msg_type,enum=msgpb.MessageType" json:"msg_type,omitempty"`
	CmdReq           *raft_cmdpb.RaftCmdRequest  `protobuf:"bytes,2,opt,name=cmd_req" json:"cmd_req,omitempty"`
	CmdResp          *raft_cmdpb.RaftCmdResponse `protobuf:"bytes,3,opt,name=cmd_resp" json:"cmd_resp,omitempty"`
	Raft             *raft_serverpb.RaftMessage  `protobuf:"bytes,4,opt,name=raft" json:"raft,omitempty"`
	KvReq            *kvrpcpb.Request            `protobuf:"bytes,5,opt,name=kv_req" json:"kv_req,omitempty"`
	KvResp           *kvrpcpb.Response           `protobuf:"bytes,6,opt,name=kv_resp" json:"kv_resp,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetMsgType() MessageType {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return MessageType_None
}

func (m *Message) GetCmdReq() *raft_cmdpb.RaftCmdRequest {
	if m != nil {
		return m.CmdReq
	}
	return nil
}

func (m *Message) GetCmdResp() *raft_cmdpb.RaftCmdResponse {
	if m != nil {
		return m.CmdResp
	}
	return nil
}

func (m *Message) GetRaft() *raft_serverpb.RaftMessage {
	if m != nil {
		return m.Raft
	}
	return nil
}

func (m *Message) GetKvReq() *kvrpcpb.Request {
	if m != nil {
		return m.KvReq
	}
	return nil
}

func (m *Message) GetKvResp() *kvrpcpb.Response {
	if m != nil {
		return m.KvResp
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "msgpb.Message")
	proto.RegisterEnum("msgpb.MessageType", MessageType_name, MessageType_value)
}

var fileDescriptor0 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x8f, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0x49, 0xf3, 0xe1, 0x70, 0x11, 0xc8, 0x1c, 0x4b, 0x14, 0x96, 0xaa, 0x62, 0xa8, 0x40,
	0x64, 0xe8, 0x5f, 0x60, 0x44, 0x74, 0xa8, 0xd8, 0xa3, 0xd2, 0x1e, 0x1d, 0xaa, 0x34, 0xae, 0x1d,
	0x22, 0xf1, 0xdb, 0x59, 0x38, 0x3b, 0x75, 0xe4, 0x81, 0xcd, 0xbe, 0xf7, 0xd1, 0x3d, 0xef, 0x41,
	0xd1, 0x9a, 0x83, 0xfa, 0xac, 0x95, 0xee, 0xfa, 0x0e, 0x53, 0xf7, 0xa9, 0xa4, 0xde, 0x7e, 0xf5,
	0xcd, 0xae, 0xdd, 0xfb, 0xa0, 0xba, 0x77, 0x13, 0x43, 0x7a, 0x20, 0x3d, 0x0d, 0x6f, 0x8e, 0x83,
	0x56, 0x3b, 0xff, 0x5d, 0xfc, 0x46, 0x20, 0xde, 0xc9, 0x98, 0xed, 0x81, 0xf0, 0x11, 0x72, 0x5e,
	0xd5, 0xf4, 0x3f, 0x8a, 0xca, 0x68, 0x1e, 0x2d, 0x6f, 0x57, 0x58, 0x8f, 0xa2, 0x0b, 0xf1, 0xc1,
	0x09, 0x3e, 0x83, 0x60, 0x49, 0xa3, 0xe9, 0x5c, 0xce, 0x18, 0x2a, 0x56, 0x55, 0x1d, 0x98, 0x37,
	0xfc, 0x7c, 0x6d, 0xf7, 0x1b, 0x3a, 0x7f, 0x93, 0xe9, 0xf1, 0x05, 0xf2, 0x11, 0x36, 0xaa, 0x8c,
	0x1d, 0xfd, 0xf0, 0x2f, 0x6d, 0x54, 0x77, 0x32, 0x84, 0x4b, 0x48, 0x6c, 0x5a, 0x26, 0xe1, 0xe2,
	0xe9, 0x00, 0x4b, 0xfb, 0xae, 0x73, 0xc8, 0x8e, 0x83, 0x2b, 0x91, 0x3a, 0x56, 0xd6, 0xfe, 0x2e,
	0xaf, 0x5e, 0x80, 0x70, 0x04, 0x9b, 0x33, 0x87, 0xdc, 0x05, 0xc8, 0xe8, 0x7b, 0x5a, 0x43, 0x11,
	0x9e, 0x96, 0x43, 0xb2, 0xee, 0x4e, 0x24, 0xaf, 0x50, 0x40, 0xcc, 0xbd, 0x64, 0x84, 0x05, 0x88,
	0x4b, 0x41, 0x39, 0xb3, 0xb9, 0xed, 0x20, 0x63, 0xbc, 0x86, 0xf4, 0x6d, 0x60, 0x93, 0x4c, 0x10,
	0x20, 0xb3, 0x4f, 0x06, 0xd2, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xdc, 0xe0, 0xc7, 0x98,
	0x01, 0x00, 0x00,
}
